import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export default function TermsOfService() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <Header />
      
      <main className="flex-1 pt-28 pb-16">
        <div className="mx-auto max-w-3xl px-4">
          <h1 className="mb-8 text-4xl font-bold tracking-tight">Terms of Service</h1>
          <p className="mb-8 text-muted-foreground">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

          <div className="space-y-8 text-foreground">
            {/* Acceptance of Terms */}
            <section>
              <h2 className="mb-4 text-2xl font-semibold">Acceptance of Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                By accessing and using ExamFromPDF, you agree to be bound by these Terms of Service. 
                If you do not agree with any part of these terms, please do not use the service. 
                No account or signup is required to use ExamFromPDF.
              </p>
            </section>

            {/* Description of the Service */}
            <section>
              <h2 className="mb-4 text-2xl font-semibold">Description of the Service</h2>
              <p className="text-muted-foreground leading-relaxed">
                ExamFromPDF is an online tool that allows users to upload PDF documents and generate 
                practice exams based on the content. The service uses artificial intelligence to 
                analyze uploaded materials and create questions for study and practice purposes.
              </p>
            </section>

            {/* Use of AI-Generated Content */}
            <section>
              <h2 className="mb-4 text-2xl font-semibold">Use of AI-Generated Content</h2>
              <p className="mb-4 text-muted-foreground leading-relaxed">
                All exams and questions generated by ExamFromPDF are created using artificial intelligence. 
                Please be aware that:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>AI-generated content may contain errors, inaccuracies, or misinterpretations</li>
                <li>Generated questions should be reviewed before use</li>
                <li>The quality of output depends on the quality and clarity of the uploaded PDF</li>
                <li>We do not guarantee the correctness or completeness of any generated content</li>
              </ul>
            </section>

            {/* Educational Use Disclaimer */}
            <section>
              <h2 className="mb-4 text-2xl font-semibold">Educational Use Disclaimer</h2>
              <p className="mb-4 text-muted-foreground leading-relaxed">
                ExamFromPDF is designed for educational and practice purposes only. The generated exams are intended to help students study and prepare for assessments.
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Generated exams are not official assessments</li>
                <li>Do not use generated content as a substitute for formal testing or evaluation</li>
                <li>Teachers and educators should review all content before distributing to students</li>
              </ul>
            </section>

            {/* User Responsibilities */}
            <section>
              <h2 className="mb-4 text-2xl font-semibold">User Responsibilities</h2>
              <p className="mb-4 text-muted-foreground leading-relaxed">
                When using ExamFromPDF, you agree to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>Only upload content you have the right to use</li>
                <li>Not upload content that is illegal, harmful, or infringes on others' rights</li>
                <li>Use the service for lawful educational purposes</li>
                <li>Review generated content for accuracy before use</li>
              </ul>
              <p className="mt-4 text-muted-foreground leading-relaxed">
                Uploaded files are stored temporarily for up to 7 days and then automatically deleted.
              </p>
            </section>

            {/* Service Availability */}
            <section>
              <h2 className="mb-4 text-2xl font-semibold">Service Availability</h2>
              <p className="text-muted-foreground leading-relaxed">
                We strive to keep ExamFromPDF available and functioning properly. However, we cannot 
                guarantee uninterrupted access to the service. The service may be temporarily unavailable 
                due to maintenance, updates, or circumstances beyond our control. We reserve the right 
                to modify or discontinue the service at any time.
              </p>
            </section>

            {/* Limitation of Liability */}
            <section>
              <h2 className="mb-4 text-2xl font-semibold">Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed">
                ExamFromPDF is provided "as is" without warranties of any kind. We are not liable for 
                any damages arising from your use of the service, including but not limited to errors 
                in generated content, loss of data, or reliance on AI-generated materials. Use the 
                service at your own discretion and always verify important information independently.
              </p>
            </section>

            {/* Changes to These Terms */}
            <section>
              <h2 className="mb-4 text-2xl font-semibold">Changes to These Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                We may update these Terms of Service from time to time. Any changes will be posted 
                on this page with an updated revision date. Continued use of the service after 
                changes are posted constitutes acceptance of the revised terms.
              </p>
            </section>

            {/* Contact */}
            <section>
              <h2 className="mb-4 text-2xl font-semibold">Contact</h2>
              <p className="text-muted-foreground leading-relaxed">
                If you have any questions about these Terms of Service, please contact us through the website.
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
